### PR TITLE
Enabling CLA

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**

### CODE REVIEW

**Review by ymotongpoo — APPROVED** [review]

**Comment by ymotongpoo** [comment]
@SergeyKanzhelev how can we enable CLA for this repo?

**Comment by SergeyKanzhelev** [comment]
I already did

**Comment by ymotongpoo** [comment]
Awesome!

**Comment by ymotongpoo** [comment]
@SergeyKanzhelev  Could you add @shirou as well?

**Pull request merged**
